# Generated by Django 3.0.5 on 2020-11-14 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import minoristaAPI.ordencompra.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mayoristaAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('minorista_aprobo', models.BooleanField(default=False)),
                ('mayorista_aprobo', models.BooleanField(default=False)),
                ('productos', djongo.models.fields.ArrayField(model_container=minoristaAPI.ordencompra.models.StockSolicitado, null=True)),
                ('mayorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mayoristaAPI.Mayorista')),
                ('minorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Minorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(default='', editable=False, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
