# Generated by Django 3.0.5 on 2020-10-06 01:12

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import mayoristaAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', editable=False, max_length=100)),
                ('last_name', models.CharField(default='', editable=False, max_length=100)),
                ('username', models.CharField(default='', editable=False, max_length=100)),
                ('contacto', models.CharField(default='', editable=False, max_length=30)),
                ('email', models.CharField(default='', editable=False, max_length=50)),
                ('password', models.CharField(default='', editable=False, max_length=50)),
                ('compraMinima', models.IntegerField(blank=True)),
                ('compraMaxima', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('mayorista', models.CharField(max_length=12)),
                ('distribuidor', models.CharField(max_length=12)),
                ('productos', djongo.models.fields.ArrayField(model_container=mayoristaAPI.models.StockPedido, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('precioPublico', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mayoristaAPI.Mayorista')),
            ],
        ),
    ]
