# Generated by Django 3.0.5 on 2020-09-20 20:44

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mayoristaAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('compraMinima', models.IntegerField()),
                ('compraMaxima', models.IntegerField()),
                ('sede', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='mayoristaAPI.Sede')),
            ],
        ),
    ]
