# Generated by Django 3.0.5 on 2020-09-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayoristaAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', editable=False, max_length=100)),
                ('last_name', models.CharField(default='', editable=False, max_length=100)),
                ('username', models.CharField(default='', editable=False, max_length=100)),
                ('contacto', models.CharField(default='', editable=False, max_length=30)),
                ('email', models.CharField(default='', editable=False, max_length=50)),
                ('password', models.CharField(default='', editable=False, max_length=50)),
                ('compraMinima', models.IntegerField(blank=True)),
                ('compraMaxima', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
