# Generated by Django 3.0.5 on 2020-09-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayoristaAPI', '0002_auto_20200920_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mayorista',
            old_name='correo',
            new_name='email',
        ),
    ]
