# Generated by Django 3.0.5 on 2020-09-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayoristaAPI', '0003_auto_20200920_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mayorista',
            name='nombre',
        ),
        migrations.AddField(
            model_name='mayorista',
            name='first_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='mayorista',
            name='last_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='mayorista',
            name='username',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='partida',
            name='imagen',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mayorista',
            name='compraMaxima',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mayorista',
            name='compraMinima',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mayorista',
            name='contacto',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='mayorista',
            name='email',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
