# Generated by Django 3.0.5 on 2020-09-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayoristaAPI', '0004_auto_20200921_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mayorista',
            name='password',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
